### ISSUE TITLE
Users should have different roles

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#12]
so that depending on that role, they are allowed to post blogs or act as an admin.

Decide if we need an extensive gem such as rolify, or if we can use a simpler solution without so much overhead.

Discuss possible solutions in slack channel and present an option to team.

Tied to #3

**Comment by ttilberg** [comment]
I'll take a stab at this. At this time, I think we'll set it up using a simple many:many model relationship between User and Role

**Comment by ttilberg** [comment]
Okay, I decided that I lied. I'm going to implement an enum based approach. [Notes for reference later...](http://railsapps.github.io/rails-authorization.html)

**Comment by ttilberg** [comment]
Notes for discussion later / research / whatever.

![image](https://cloud.githubusercontent.com/assets/7969650/8332049/524e5800-1a51-11e5-92eb-2a47b786bf0c.png)

So what happens if there are name collisions, since it isn't `User.role(name)`.

For instance, consider:

```
enum role: [:good, :bad, :ugly]
enum hotdog_preference: [:good, :awesomesauce, :omfgyay]
```

Suddenly there is conflict with `User.good`

This is obviously a fringe, ridiculous case, but it still exists. Find out how Ruby/Rails/ActiveRecord handles this condition.

**Comment by claytonflesher** [comment]
Closing issue.
