### ISSUE TITLE
Learning OOP + architecture guidelines

### ISSUE THREAD

**Issue by allanbreyes** [code-newbies/ruby-monday-blog#66]
A few intermediate concepts that I've been struggling with are composition over inheritance, dependency injection/inversion, and generally SOLID principles.  I'm hoping that we might also use this project as a vehicle to also practice some high-level concepts of good OOP design.

So, I'm wondering if people have thoughts on this as well, and if anything in the code base can be refactored to this.  If possible, can we maybe stick to some loose guidelines, i.e.
- avoid concerns where applicable (type of inheritance)
- all things being equal, choose composition over inheritance (I always naturally gravitate towards inheritance, and haven't really developed an eye for where to apply composition. Would love help, here!)
- avoid coupling models together; use service objects, policies, form objects, etc.

And some from Sandi Metz:
- Classes can be no longer than one hundred lines of code.
- Methods can be no longer than five lines of code.
- Pass no more than four parameters into a method. Hash options are parameters.
- Controllers can instantiate only one object. Therefore, views can only know about one instance variable and views should only send messages to that object (@object.collaborator.value is not allowed).

Thoughts?

Resources:
- https://en.wikipedia.org/wiki/SOLID_(object-oriented_design)
- Sandi Metz's POODR
- https://robots.thoughtbot.com/sandi-metz-rules-for-developers
- http://naildrivin5.com/blog/2012/12/19/re-use-in-oo-inheritance.html
- (paid) thoughtbot's Upcase Episode 33 (Composition over Inheritance)
- http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/

**Comment by matugm** [comment]
I have lots of thoughts! I have been focusing on learning about code quality / best practices / OOP for a while.
- I have read a bit of the original [Design patterns](http://www.amazon.co.uk/Design-patterns-elements-reusable-object-oriented/dp/0201633612) book (it's VERY dry so I didn't feel like I wanted to keep reading). One thing that I took note on is that the authors recommend 'Prefer composition over inheritance'. Inheritance has some problems: for example, you can only inherit from one class at a time in Ruby. When you create a sub-class you are expected to provide the same interface than the super-class (that means the same set of methods), the last thing you want is to have type checks all over your code. Inheritance also makes things harder to change.
- I agree with the first three guide-lines (that's intentional, I don't want to call them rules) from Sandi. The last one about controllers is not very practical in my opinion.
- Form objects, presenters, etc. Are all good but that doesn't mean you need to use them everywhere (refer to my next bullet-point).
- I believe in the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle)
- I wrote this which has some examples: https://gist.github.com/matugm/58eca881bbdb4f833af3#file-compo-md
- TDD can help with design, it's not only about making sure your code is working.
- Personally I don't think a rails app is the ideal environment to learn more about these concepts. Rails already has it's own things and complexity to deal with.
- Keeping things DRY (Don't Repeat Yourself) is usually a good idea.
- Good naming of variables and functions makes things easier. If you find the need to add a comment, maybe it just needs a better name, or extracting that code into an [intention-revealing](http://objectmentor.com/resources/articles/Naming.pdf) method.
- [Code smells](https://en.wikipedia.org/wiki/Code_smell) can help you identify when something is wrong. 
- Lots of other stuff, there are entire books on the subject :)

**Comment by abinoam** [comment]
@allanbreyes have you read the "Confident Ruby" by Avdi Grimm?
http://www.confidentruby.com/
It's much "direct to the point". 

I'm searching an opportunity to re-read the Sandi Metz book. I really enjoyed (although I didn't internalized all the book content. I definitely have to read again).

Of note is this post of Codeclimate 
http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/
